### ISSUE TITLE
The experimental results of this attack are incorrect：distortion too large！

### ISSUE THREAD

**Issue by dtyi01** [Farhamdur/CGBA#2]
When running your CGBA code, I found that the distortion for targeted attacks is significantly larger, which does not align with the results described in the paper. I would like to know if there are any issues with the uploaded code. Attached is a screenshot of the results I obtained from running the code.
![image](https://github.com/Farhamdur/CGBA/assets/144131502/0dc20d00-e577-42bf-a571-3c09a252ac98)

**Comment by Farhamdur** [comment]
I think the code is fine. You shouldn't judge it based on a single sample. Please run the code for at least 100 samples before drawing your conclusion.
